### ISSUE TITLE
copying a table

### ISSUE THREAD

**Issue by lhaycock** [joewheaton-org/gis#1]
@joewheaton Do you know how to copy the table at the bottom of the page [here](http://gis.joewheaton.org/about) into Typora?  Maybe @philipbaileynar has any suggestions?  I right clicked and took a look at the frame source but wasn't sure if it is as simple as copy and pasting everything there.

**Comment by philipbaileynar** [comment]
1. Try this https://www.tablesgenerator.com/markdown_tables
1. Copy from web page and paste into Google Sheet. Then copy into Typora.
